### ISSUE TITLE
Running MPI enabled coreneuron without srun/mpirun causes Floating point exception (with HPE-MPI)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#305]
While running on BB5, I see following:

```
$ ./x86_64/special-core -e 100 -d testkindat/ --gpu

 Duke, Yale, and the BlueBrain Project -- Copyright 1984-2019
 version id unimplemented

....

 Start time (t) = 0

 Memory (MBs) :  After mk_spikevec_buffer : Max 196.2578, Min 196.2578, Avg 196.2578
Floating point exception
```

And enabling FPE with GDB shows:

```
 >> gdb ./x86_64/special-core

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
...

(gdb) r -e 100 -d testkindat/ --gpu
Starting program: /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/testcorenrn/./x86_64/special-core -e 100 -d testkindat/ --gpu
.....


Program received signal SIGFPE, Arithmetic exception.
0x00007fffed12b0b2 in MPI_SGI_comm_fetch (comm=comm@entry=1) at comm.c:36
36	comm.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.6.x86_64 libbitmask-2.0-721r1.rhel77hpe.x86_64 libcpuset-1.0-721r191009T2000.rhel77hpe.x86_64
(gdb) bt
#0  0x00007fffed12b0b2 in MPI_SGI_comm_fetch (comm=comm@entry=1) at comm.c:36
#1  0x00007fffed1352f7 in MPI_SGI_comm_get (comm=1) at ../../../../include/comm.h:182
#2  MPI_SGI_comm_is_inter (comm=1) at ../../../../include/comm.h:198
#3  PMPI_Comm_split_type (comm=1, split_type=1, key=0, info=0, newcomm=0x7fffffff7c80) at comm_split.c:606
#4  0x0000000000481d6e in nrnmpi_local_rank () at /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/coreneuron/coreneuron/mpi/nrnmpi.cpp:237
#5  0x000000000044bd9c in coreneuron::setup_nrnthreads_on_device (threads=0x1414ab0, nthreads=2)
    at /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/coreneuron/coreneuron/gpu/nrn_acc_manager.cpp:961
#6  0x0000000000445927 in coreneuron::nrn_init_and_load_data (argc=6, argv=0x7fffffff8da8, is_mapping_needed=0 '\000', nrnmpi_under_nrncontrol=<optimized out>,
    run_setup_cleanup=1 '\001') at /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/coreneuron/coreneuron/apps/main1.cpp:290
#7  0x000000000042d30c in run_solve_core (argc=6, argv=0x7fffffff8da8) at /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/coreneuron/coreneuron/apps/main1.cpp:468
#8  0x00000000004141b0 in solve_core (argc=6, argv=0x7fffffff8da8)
    at /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/coreneuron/build_master/install/share/coreneuron/enginemech.cpp:40
#9  0x0000000000414189 in main (argc=1, argv=0x7fffed489809 <mpi_sgi_thread_safe>)
    at /gpfs/bbp.cscs.ch/data/project/proj16/kumbhar/pramod_scratch/coreneuron/build_master/install/share/coreneuron/coreneuron.cpp:34
```

**Comment by pramodk** [comment]
Seems this has been fixed already. Cant reproduce on BB5 with latest master.
