### ISSUE TITLE
Problem running sample code from github page to test  CoreNeuron

### ISSUE THREAD

**Issue by aweaver1fandm** [BlueBrain/CoreNeuron#742]
**Describe the issue**
Attempting to run the sample code under the Running Simulations section of the github page
which is supposed to first run a model in Neuron then in CoreNeuron.  When I do, it fails saying cannot find CoreNeuron library

**To Reproduce**
python3 test.py 
NEURON: Could not find CoreNEURON library
 near line 0
 create soma
            ^
        ParallelContext[0].psolve(10)
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    pc.psolve(h.tstop)
RuntimeError: hocobj_call error

I also put the code into an interactive python interpreter line-by-line with no issues until the line
pc.psolve(h.tstop)

**Logs**
I built neuron on an Ubuntu 20.04 system with CoreNeuron support with the following cmake command:

cmake .. -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_RX3D=OFF -DCORENRN_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX=/opt/nrn -DCMAKE_C_COMPILER=nvc -DCMAKE_CXX_COMPILER=nvc++ -DCMAKE_CUDA_COMPILER=nvcc -DReadline_LIBRARY=/lib/x86_64-linux-gnu/libreadline.so.8

It seemed to make fine.  I can also import CoreNeuron just fine when have an interactive python session going as seen from this output
python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from neuron import coreneuron
>>> coreneuron.enable = True
>>> help(coreneuron)
Help on coreneuron object:

class coreneuron(builtins.object)
 |  CoreNEURON configuration values.
 |  
 |  An instance of this class stands in as the `neuron.coreneuron` module. Using
 |  a class instead of a module allows getter/setter methods to be used, which
 |  lets us ensure its properties have consistent types and values.
 |  
 |  Attributes
 |  ----------
 |  cell_permute
 |  enable
 |  file_mode
 |  gpu
 |  prcellstate
 |  verbose
 |  warp_balance
 |  
 |  Examples
 |  --------
 |  >>> from neuron import coreneuron
 |  >>> coreneuron.enable = True
 |  >>> coreneuron.enable
 |  True
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |  
 |  nrncore_arg(self, tstop)
 |      Return str that can be used for pc.nrncore_run(str)
 |      based on user properties and current NEURON settings.
 |      :param tstop: Simulation time (ms)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  cell_permute
 |      Get/set the cell permutation order. Possible values are:
 |      - 0: no permutation (requires gpu = False)
 |      - 1: optimize node adjacency
 |      - 2: optimise parent node adjacency (requires gpu = True)
 |  
 |  enable
 |      Use CoreNEURON when calling ParallelContext.psolve(tstop).
 |  
 |  file_mode
 |      Run via file transfer mode instead of in-memory transfer.
 |  
 |  gpu
 |      Activate GPU computation in CoreNEURON.
 |  
 |  num_gpus
 |      Get/set the number of GPU to use.
 |      0 means to use all that are avilable.
 |  
 |  prcellstate
 |      Output prcellstate information for the given gid at t=0 and at tstop.
 |      A value of -1 indicates no prcellstate output will be generated.
 |  
 |  verbose
 |      Configure the verbosity of CoreNEURON. Possible values are:
 |      - 0: quiet/no output
 |      - 1: error
 |      - 2: info (default)
 |      - 3: debug
 |  
 |  warp_balance
 |      Number of warps to balance. A value of 0 indicates no balancing
 |      should be done. This has no effect without cell_permute = 2 (and
 |      therefore gpu = True).

**Comment by nrnhines** [comment]
> cannot find CoreNeuron library

The x86_64 folder that was constructed by ```nrnivmodl -coreneuron ...``` must be in the same folder where you launched python3
Alternatively , find the full path to ```libcorenrnmech.so``` and use that for the CORENEURONLIB environment variable. eg.
```
export CORENEURONLIB=/home/hines/models/hnn/hnn_core/mod/x86_64/libcorenrnmech.so
```

**Comment by aweaver1fandm** [comment]
I apologize because I am relatively unfamiliar with the Neuron workflow.  I am trying to set the software up for a researcher and I am just trying to test if the software is working.  Initially I did not run nrnivmodl because I don't have any .mod files.  I was under the possibly erroneous impression that the sample python code on the main GitHub page for CoreNeuron should execute without needing to run nrnivmodl assuming CoreNeuron is setup properly.

Just in case, I ran nrnivmodl -coreneuron . in the directory where I am calling python test.py  The output seemed to build without error and created an x86_64 directory.  However, it did not have a libcorenrnmech.so file.  Output is:

:~# ls
cuda_11.3.0_465.19.01_linux.run  nrn  nvhpc-2022_22.1_amd64.deb  nvhpc-22-1_22.1_amd64.deb  snap  test.py

:~# nrnivmodl -coreneuron .
/root
ls: cannot access '*.mod': No such file or directory
Mod files:

Creating x86_64 directory for .o files.

COBJS=''
WARNING: No mod files found, compiling default ones only!
[INFO] Running: make -j4 -f /opt/nrn/share/coreneuron/nrnivmodl_core_makefile ROOT=/opt/nrn MODS_PATH=x86_64/corenrn/mod2c BUILD_TYPE=STATIC NRN_PRCELLSTATE=0
Default NMODL flags: 
Translating x86_64/corenrn/mod2c/hh.mod into x86_64/corenrn/mod2c//hh.cpp
Translating x86_64/corenrn/mod2c/exp2syn.mod into x86_64/corenrn/mod2c//exp2syn.cpp
Translating x86_64/corenrn/mod2c/expsyn.mod into x86_64/corenrn/mod2c//expsyn.cpp
cvode_emit=0 cvode_not_allowed=0
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
diff: x86_64/corenrn/mod2c/_mod_func.cpp: No such file or directory
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/netstim.mod into x86_64/corenrn/mod2c//netstim.cpp
Translating x86_64/corenrn/mod2c/passive.mod into x86_64/corenrn/mod2c//passive.cpp
Translating x86_64/corenrn/mod2c/stim.mod into x86_64/corenrn/mod2c//stim.cpp
Translating x86_64/corenrn/mod2c/pattern.mod into x86_64/corenrn/mod2c//pattern.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
cvode_emit=0 cvode_not_allowed=0
Notice: ARTIFICIAL_CELL is a synonym for POINT_PROCESS which hints that it
only affects and is affected by discrete events. As such it is not
located in a section and is not associated with an integrator
cvode_emit=0 cvode_not_allowed=0
Notice: ARTIFICIAL_CELL is a synonym for POINT_PROCESS which hints that it
only affects and is affected by discrete events. As such it is not
located in a section and is not associated with an integrator
Thread Safe
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/svclmp.mod into x86_64/corenrn/mod2c//svclmp.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
/root
=> Binary creating x86_64/special-core
/opt/nrn/share/coreneuron/coreneuron.cpp:
[INFO] MOD files built successfully for CoreNEURON
 -> Compiling mod_func.cpp
 => LINKING shared library ./libnrnmech.so
 => LINKING executable ./special LDFLAGS are:    /lib/x86_64-linux-gnu/libreadline.so.8 -Wl,-rpath,/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/libpython3.8.so -Wl,-rpath,/usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so -Wl,-rpath,/usr/lib/x86_64-linux-gnu/openmpi/lib
/opt/nrn/share/nrn/nrnmain.cpp:
Successfully created x86_64/special

:~# python3 test.py 
NEURON: Could not find CoreNEURON library
 near line 0
 create soma
            ^
        ParallelContext[0].psolve(10)
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    pc.psolve(h.tstop)
RuntimeError: hocobj_call error

:~# cd x86_64/
:~/x86_64# ls
corenrn  libcorenrnmech.a  libnrnmech.so  makemod2c_inc  mod_func.cpp  mod_func.o  nrnmain.o  special  special-core

**Comment by iomaganaris** [comment]
Dear @aweaver1fandm ,

The issue might be that the `CoreNEURON` library cannot be dynamically loaded when launching the simulation using the `python` executable in a GPU build as yours due to technical restrictions.
Instead I would suggest running the `test.py` using the `NEURON` executable you created called `special`.
To be more specific:
```
./x86_64/special -python test.py
```
Please try this and let us know if there are any issues. 
I am also guessing you're using the `test.py` from [here](https://github.com/BlueBrain/CoreNeuron#running-simulations) so if you want to execute the simulation in a GPU you should also add in the `test.py` the following:
```
coreneuron.gpu = True
```
after enabling the `coreneuron.enable = True` option.

**Comment by aweaver1fandm** [comment]
Yes I was using the code you linked to.  The dynamic library is indeed the issue.  I ran it with _special_ as you suggested and CoreNeuron ran fine both with and without GPU.  Thank you.

**Comment by iomaganaris** [comment]
Great! I've also created a PR for the documentation to clarify this part. Thanks a lot for the feedback and let us know if you need any further help with NEURON or CoreNEURON. 
Feel free to close the issue if there is nothing else needed
