### ISSUE TITLE
perl binary path is encoded in the wheel distribution

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#791]
**Describe the issue**

`nrnivmodl-core` depends on perl. In case of wheel distribution perl path is encoded from the machine where wheel is built.

**To Reproduce**

* Install MacOS coreneuron wheel
* `nrnivmodl -coreneuron` gives
```console
 → nrnivmodl -coreneuron -incflags "-I/usr/local/opt/openssl@3/include" mod
INFO : Using neuron-nightly Package (Developer Version)
/usr/bin/xcrun
/Users/kumbhar/Downloads/mechanism_cpp/tqperf
Mod files: "mod/invlfire.mod"

Creating x86_64 directory for .o files.

COBJS=''
/Users/kumbhar/Downloads/mechanism_cpp/v/lib/python3.9/site-packages/neuron/.data/bin/nrnivmodl-core: line 22: /usr/local/bin/perl: No such file or directory
Traceback (most recent call last):
  File "/Users/kumbhar/Downloads/mechanism_cpp/v/bin/nrnivmodl", line 94, in <module>
    subprocess.check_call([exe, *sys.argv[1:]])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/kumbhar/Downloads/mechanism_cpp/v/lib/python3.9/site-packages/neuron/.data/bin/nrnivmodl', '-coreneuron', '-incflags', '-I/usr/local/opt/openssl@3/include', 'mod']' returned non-zero exit status 127.
``` 

Perl is available on the user machine:

```console
± |master U:2 ?:1 ✗| → ls -l /usr/local/bin/perl
ls: /usr/local/bin/perl: No such file or directory

± |master U:2 ?:1 ✗| → which perl
/usr/bin/perl
```

**Expected behavior**

Perl path shouldn't be hardcoded but should be picked up from user machine.

**Comment by olupton** [comment]
Closed by https://github.com/BlueBrain/CoreNeuron/pull/800.
